export const BACKMODECHANGE = 'BACKMODECHANGE';
export const SETUSERINFO = "SETUSERINFO";
export const ADDCATEGORY = "ADDCATEGORY";
export const ADDCATEGORYTAG = "ADDCATEGORYTAG";
export const CLEARCATEGORY = "CLEARCATEGORY";